// SPDX-FileCopyrightText: 2023 Don Geronimo <https://sentamal.in/>
// SPDX-License-Identifier: GPL-3.0-or-later

/**
 * A list of 3-digit nationality codes available in ISO 3166-1 and
 *     ICAO 9303-3.
 * @readonly
 * @enum { Symbol }
 */
export const NationalityCode = Object.freeze({
  // Official ISO 3166-1 alpha-3 nationality codes
  ABW: Symbol.for("Aruba"),
  AFG: Symbol.for("Afghanistan"),
  AGO: Symbol.for("Angola"),
  AIA: Symbol.for("Anguilla"),
  ALA: Symbol.for("Åland Islands"),
  ALB: Symbol.for("Albania"),
  AND: Symbol.for("Andorra"),
  ARE: Symbol.for("United Arab Emirates"),
  ARG: Symbol.for("Argentina"),
  ARM: Symbol.for("Armenia"),
  ASM: Symbol.for("American Samoa"),
  ATA: Symbol.for("Antarctica"),
  ATF: Symbol.for("French Southern Territories"),
  ATG: Symbol.for("Antigua and Barbuda"),
  AUS: Symbol.for("Australia"),
  AUT: Symbol.for("Austria"),
  AZE: Symbol.for("Azerbaijan"),
  BDI: Symbol.for("Burundi"),
  BEL: Symbol.for("Belgium"),
  BEN: Symbol.for("Benin"),
  BES: Symbol.for("Bonaire, Sint Eustatius, and Saba"),
  BFA: Symbol.for("Burkina Faso"),
  BGD: Symbol.for("Bangladesh"),
  BGR: Symbol.for("Bulgaria"),
  BHR: Symbol.for("Bahrain"),
  BHS: Symbol.for("Bahamas"),
  BIH: Symbol.for("Bosnia and Herzegovina"),
  BLM: Symbol.for("Saint Barthélemy"),
  BLR: Symbol.for("Belarus"),
  BLZ: Symbol.for("Belize"),
  BMU: Symbol.for("Bermuda"),
  BOL: Symbol.for("Bolivia (Plurinational State of)"),
  BRA: Symbol.for("Brazil"),
  BRB: Symbol.for("Barbados"),
  BRN: Symbol.for("Brunei Darussalam"),
  BTN: Symbol.for("Bhutan"),
  BVT: Symbol.for("Bouvet Island"),
  BWA: Symbol.for("Botswana"),
  CAF: Symbol.for("Central African Republic"),
  CAN: Symbol.for("Canada"),
  CCK: Symbol.for("Cocos (Keeling) Islands"),
  CHE: Symbol.for("Switzerland"),
  CHL: Symbol.for("Chile"),
  CHN: Symbol.for("China"),
  CIV: Symbol.for("Côte d'Ivoire"),
  CMR: Symbol.for("Cameroon"),
  COD: Symbol.for("Congo, Democratic Republic of the"),
  COG: Symbol.for("Congo"),
  COK: Symbol.for("Cook Islands"),
  COL: Symbol.for("Colombia"),
  COM: Symbol.for("Comoros"),
  CPV: Symbol.for("Cabo Verde"),
  CRI: Symbol.for("Costa Rica"),
  CUB: Symbol.for("Cuba"),
  CUW: Symbol.for("Curaçao"),
  CXR: Symbol.for("Christmas Island"),
  CYM: Symbol.for("Cayman Islands"),
  CYP: Symbol.for("Cyprus"),
  CZE: Symbol.for("Czechia"),
  DEU: Symbol.for("Germany"),
  DJI: Symbol.for("Djibouti"),
  DMA: Symbol.for("Dominica"),
  DNK: Symbol.for("Denmark"),
  DOM: Symbol.for("Dominican Republic"),
  DZA: Symbol.for("Algeria"),
  ECU: Symbol.for("Ecuador"),
  EGY: Symbol.for("Egypt"),
  ERI: Symbol.for("Eritrea"),
  ESH: Symbol.for("Western Sahara"),
  ESP: Symbol.for("Spain"),
  EST: Symbol.for("Estonia"),
  ETH: Symbol.for("Ethiopia"),
  FIN: Symbol.for("Finland"),
  FJI: Symbol.for("Fiji"),
  FLK: Symbol.for("Falkland Islands (Malvinas)"),
  FRA: Symbol.for("France"),
  FRO: Symbol.for("Faroe Islands"),
  FSM: Symbol.for("Micronesia (Federated States of)"),
  GAB: Symbol.for("Gabon"),
  GBR: Symbol.for("United Kingdom of Great Britain and Northern Ireland"),
  GEO: Symbol.for("Georgia"),
  GGY: Symbol.for("Guernsey"),
  GHA: Symbol.for("Ghana"),
  GIB: Symbol.for("Gibraltar"),
  GIN: Symbol.for("Guinea"),
  GLP: Symbol.for("Guadeloupe"),
  GMB: Symbol.for("Gambia"),
  GNB: Symbol.for("Guinea-Bissau"),
  GNQ: Symbol.for("Equatorial Guinea"),
  GRC: Symbol.for("Greece"),
  GRD: Symbol.for("Grenada"),
  GRL: Symbol.for("Greenland"),
  GTM: Symbol.for("Guatemala"),
  GUF: Symbol.for("French Guiana"),
  GUM: Symbol.for("Guam"),
  GUY: Symbol.for("Guyana"),
  HKG: Symbol.for("Hong Kong"),
  HMD: Symbol.for("Heard Island and McDonald Islands"),
  HND: Symbol.for("Honduras"),
  HRV: Symbol.for("Croatia"),
  HTI: Symbol.for("Haiti"),
  HUN: Symbol.for("Hungary"),
  IDN: Symbol.for("Indonesia"),
  IMN: Symbol.for("Isle of Man"),
  IND: Symbol.for("India"),
  IOT: Symbol.for("British Indian Ocean Territory"),
  IRL: Symbol.for("Ireland"),
  IRN: Symbol.for("Iran (Islamic Republic of)"),
  IRQ: Symbol.for("Iraq"),
  ISL: Symbol.for("Iceland"),
  ISR: Symbol.for("Israel"),
  ITA: Symbol.for("Italy"),
  JAM: Symbol.for("Jamaica"),
  JEY: Symbol.for("Jersey"),
  JOR: Symbol.for("Jordan"),
  JPN: Symbol.for("Japan"),
  KAZ: Symbol.for("Kazakhstan"),
  KEN: Symbol.for("Kenya"),
  KGZ: Symbol.for("Kyrgyzstan"),
  KHM: Symbol.for("Cambodia"),
  KIR: Symbol.for("Kiribati"),
  KNA: Symbol.for("Saint Kitts and Nevis"),
  KOR: Symbol.for("Korea, Republic of"),
  KWT: Symbol.for("Kuwait"),
  LAO: Symbol.for("Lao People's Democratic Republic"),
  LBN: Symbol.for("Lebanon"),
  LBR: Symbol.for("Liberia"),
  LBY: Symbol.for("Libya"),
  LCA: Symbol.for("Saint Lucia"),
  LIE: Symbol.for("Liechtenstein"),
  LKA: Symbol.for("Sri Lanka"),
  LSO: Symbol.for("Lesotho"),
  LTU: Symbol.for("Lithuania"),
  LUX: Symbol.for("Luxembourg"),
  LVA: Symbol.for("Latvia"),
  MAC: Symbol.for("Macao"),
  MAF: Symbol.for("Saint Martin (French part)"),
  MAR: Symbol.for("Morocco"),
  MCO: Symbol.for("Monaco"),
  MDA: Symbol.for("Moldova, Republic of"),
  MDG: Symbol.for("Madagascar"),
  MDV: Symbol.for("Maldives"),
  MEX: Symbol.for("Mexico"),
  MHL: Symbol.for("Marshall Islands"),
  MKD: Symbol.for("North Macedonia"),
  MLI: Symbol.for("Mali"),
  MLT: Symbol.for("Malta"),
  MMR: Symbol.for("Myanmar"),
  MNE: Symbol.for("Montenegro"),
  MNG: Symbol.for("Mongolia"),
  MNP: Symbol.for("Northern Mariana Islands"),
  MOZ: Symbol.for("Mozambique"),
  MRT: Symbol.for("Mauritania"),
  MSR: Symbol.for("Montserrat"),
  MTQ: Symbol.for("Martinique"),
  MUS: Symbol.for("Mauritius"),
  MWI: Symbol.for("Malawi"),
  MYS: Symbol.for("Malaysia"),
  MYT: Symbol.for("Mayotte"),
  NAM: Symbol.for("Namibia"),
  NCL: Symbol.for("New Caledonia"),
  NER: Symbol.for("Niger"),
  NFK: Symbol.for("Norfolk Island"),
  NGA: Symbol.for("Nigeria"),
  NIC: Symbol.for("Nicaragua"),
  NIU: Symbol.for("Niue"),
  NLD: Symbol.for("Netherlands, Kingdom of the"),
  NOR: Symbol.for("Norway"),
  NPL: Symbol.for("Nepal"),
  NRU: Symbol.for("Nauru"),
  NZL: Symbol.for("New Zealand"),
  OMN: Symbol.for("Oman"),
  PAK: Symbol.for("Pakistan"),
  PAN: Symbol.for("Panama"),
  PCN: Symbol.for("Pitcairn"),
  PER: Symbol.for("Peru"),
  PHL: Symbol.for("Philippines"),
  PLW: Symbol.for("Palau"),
  PNG: Symbol.for("Papua New Guinea"),
  POL: Symbol.for("Poland"),
  PRI: Symbol.for("Puerto Rico"),
  PRK: Symbol.for("Korea (Democratic People's Republic of)"),
  PRT: Symbol.for("Portugal"),
  PRY: Symbol.for("Paraguay"),
  PSE: Symbol.for("Palestine, State of"),
  PYF: Symbol.for("French Polynesia"),
  QAT: Symbol.for("Qatar"),
  REU: Symbol.for("Réunion"),
  ROU: Symbol.for("Romania"),
  RUS: Symbol.for("Russian Federation"),
  RWA: Symbol.for("Rwanda"),
  SAU: Symbol.for("Saudi Arabia"),
  SDN: Symbol.for("Sudan"),
  SEN: Symbol.for("Senegal"),
  SGP: Symbol.for("Singapore"),
  SGS: Symbol.for("South Georgia and the South Sandwich Islands"),
  SHN: Symbol.for("Saint Helena, Ascension, and Tristan de Cunha"), 
  SJM: Symbol.for("Svalbard and Jan Mayen"),
  SLB: Symbol.for("Solomon Islands"),
  SLE: Symbol.for("Sierra Leone"),
  SLV: Symbol.for("El Salvador"),
  SMR: Symbol.for("San Marino"),
  SOM: Symbol.for("Somalia"),
  SPM: Symbol.for("Saint Pierre and Miquelon"),
  SRB: Symbol.for("Serbia"),
  SSD: Symbol.for("South Sudan"),
  STP: Symbol.for("Sao Tome and Principe"),
  SUR: Symbol.for("Suriname"),
  SVK: Symbol.for("Slovakia"),
  SVN: Symbol.for("Slovenia"),
  SWE: Symbol.for("Sweden"),
  SWZ: Symbol.for("Eswatini"),
  SXM: Symbol.for("Sint Maarten (Dutch part)"),
  SYC: Symbol.for("Seychelles"),
  SYR: Symbol.for("Syrian Arab Republic"),
  TCA: Symbol.for("Turks and Caicos Islands"),
  TCD: Symbol.for("Chad"),
  TGO: Symbol.for("Togo"),
  THA: Symbol.for("Thailand"),
  TJK: Symbol.for("Tajikistan"),
  TKL: Symbol.for("Tokelau"),
  TKM: Symbol.for("Turkmenistan"),
  TLS: Symbol.for("Timor-Leste"),
  TON: Symbol.for("Tonga"),
  TTO: Symbol.for("Trinidad and Tobago"),
  TUN: Symbol.for("Tunisia"),
  TUR: Symbol.for("Türkiye"),
  TUV: Symbol.for("Tuvalu"),
  TWN: Symbol.for("Taiwan, Province of China"),
  TZA: Symbol.for("Tanzania, United Republic of"),
  UGA: Symbol.for("Uganda"),
  UKR: Symbol.for("Ukraine"),
  UMI: Symbol.for("United States Minor Outlying Islands"),
  URY: Symbol.for("Uruguay"),
  USA: Symbol.for("United States of America"),
  UZB: Symbol.for("Uzbekistan"),
  VAT: Symbol.for("Holy See"),
  VCT: Symbol.for("Saint Vincent and the Grenadines"),
  VEN: Symbol.for("Venezuela (Bolivarian Republic of)"),
  VGB: Symbol.for("Virgin Islands (British)"),
  VIR: Symbol.for("Virgin Islands (U.S.)"),
  VNM: Symbol.for("Viet Nam"),
  VUT: Symbol.for("Vanuatu"),
  WLF: Symbol.for("Wallis and Futuna"),
  WSM: Symbol.for("Samoa"),
  YEM: Symbol.for("Yemen"),
  ZAF: Symbol.for("South Africa"),
  ZMB: Symbol.for("Zambia"),
  ZWE: Symbol.for("Zimbabwe"),

  // Codes not included in ISO 3166-1
  GBD: Symbol.for("British Overseas Territories Citizen"),
  GBN: Symbol.for("British National (Overseas)"),
  GBO: Symbol.for("British Overseas Citizen"),
  GBP: Symbol.for("British Protected Person"),
  GBS: Symbol.for("British Subject"),
  RKS: Symbol.for("Republic of Kosovo"),

  // Codes reserved by ISO 3166/MA
  EUE: Symbol.for("European Union (EU)"),

  // Codes used in UN Travel Documents
  UNO: Symbol.for("United Nations Organization"),
  UNA: Symbol.for("United Nations Specialized Agency"),
  UNK: Symbol.for("United Nations Interim Administration Mission in Kosovo"),

  // Other issuing authorities
  XBA: Symbol.for("African Development Bank (ADB)"),
  XIM: Symbol.for("African Export-Import Bank (AFREXIM)"),
  XCC: Symbol.for("Caribbean Community (CARICOM)"),
  XCE: Symbol.for("Council of Europe"),
  XCO: Symbol.for("Common Market for Eastern and Southern Africa (COMESA)"),
  XEC: Symbol.for("Economic Community of West African States (ECOWAS"),
  XPO: Symbol.for("International Criminal Police Organization (INTERPOL)"),
  XES: Symbol.for("Organization of Eastern Caribbean States (OECS)"),
  XMP: Symbol.for("Parliamentary Assembly of the Mediterranean (PAM)"),
  XOM: Symbol.for("Sovereign Military Order of Malta"),
  XDC: Symbol.for("Southern African Development Community"),

  // Persons without a defined nationality
  XXA: Symbol.for("Stateless Person"),
  XXB: Symbol.for("Refugee (defined in Article 1 of the 1951 Convention)"),
  XXC: Symbol.for("Refugee (not defined under code XXB)"),
  XXX: Symbol.for("Person of Unspecified Nationality"),

  // Specimen Documents
  UTO: Symbol.for("Utopia"),

  // Used by ICAO
  IAO: Symbol.for("International Civil Aviation Organization (ICAO)"),
});
